# WE dont directly create pods, instead we use depl.yaml files for automatic self heal and creation of pods.
apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: sundeepcharan/posts:0.0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
