apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: sundeepcharan/posts
---
# The Cluster IP since being one-one for every deployment, is going to be written on the same deployment file.
apiVersion: v1
kind: Service
metadata:
  name: posts-srv-clusterip
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: posts-port-clusterip
