apiVersion: skaffold/v2alpha3
kind: Confg
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false # We put this false to not to push the image automatically to docker hub
    # The following codes mention to either change the files in place if any of the mentioned file extension in src changes, or just rebuild the enitre docker image.
  artifacts:
    - image: sundeepcharan/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: sundeepcharan/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sundeepcharan/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sundeepcharan/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sundeepcharan/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sundeepcharan/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
