apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: sundeepcharan/comments
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
# The Cluster IP since being one-one for every deployment, is going to be written on the same deployment file.
apiVersion: v1
kind: Service
metadata:
  name: comments-srv-clusterip
spec:
  type: ClusterIP
  selector:
    app: comments
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: comments-port-clusterip
