apiVersion: v1
kind: Service
metadata:
  name: comments-srv-nodeport
spec:
  type: NodePort
  selector:
    app: comments
  ports:
    - port: 9998
      targetPort: 9998
      name: comments-port-nodeport
      protocol: TCP
