apiVersion: v1
kind: Service
metadata:
  name: posts-srv-nodeport
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - port: 9998
      targetPort: 9998
      name: posts-port-nodeport
      protocol: TCP
