apiVersion: v1
kind: Service
metadata:
  name: moderation-srv-nodeport
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - port: 9995
      targetPort: 9995
      name: moderation-port-nodeport
      protocol: TCP
