apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: sundeepcharan/moderation
---
# The Cluster IP since being one-one for every deployment, is going to be written on the same deployment file.
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv-clusterip
spec:
  type: ClusterIP
  selector:
    app: moderation
  ports:
    - port: 9995
      targetPort: 9995
      protocol: TCP
      name: moderation-port-clusterip
