apiVersion: v1
kind: Service
metadata:
  name: query-srv-nodeport
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - port: 9997
      targetPort: 9997
      name: query-port-nodeport
      protocol: TCP
